sync-with-github:
  # before_script:
  #   - git config --global user.name "${GITHUB_USER_NAME}"
  #   - git config --global user.email "${GITHUB_USER_EMAIL}"
  script:
    - git remote add github https://$ACCESS_TOKEN@github.com/olcortesb/mimic-src.git
    - git checkout master
    - git status
    - git push github master